import Section from "./Section";
import Heading from "./Heading";

const PrivacyPolicy = () => {
  return (
    <Section id="privacy-policy">
      <div className="container relative z-2">
        <Heading
          className="md:max-w-md lg:max-w-2xl mx-auto text-center -mb-5" // Center the heading
          title="Privacy Policy for Third-Party API Usage"
        />

        <div className="prose prose-lg mx-auto my-10">
          <p>
            At Bajaj Finserv’s AURA.ai, we prioritise the privacy and security
            of our users’ data. To enhance the functionality of our platform, we
            utilise several third-party APIs to generate video content, images,
            quizzes, and refined summaries. We have carefully selected APIs that
            align with industry standards for data protection and privacy. This
            section outlines how these third-party services handle user data, as
            well as our compliance with data privacy regulations.
          </p>

          {/* Section for Pixabay API */}
          <h2>1. Pixabay API</h2>
          <p>
            We use the Pixabay API to generate videos based on the keywords
            extracted from user documents. Pixabay provides access to a library
            of stock videos that are integrated into the final video content
            generated on our platform.
          </p>
          <ul>
            <li>
              <strong>Data Usage:</strong> Pixabay does not collect personal
              data from AURA.ai users. The API interaction is limited to keyword
              input for retrieving relevant video content.
            </li>
            <li>
              <strong>Privacy Policy:</strong>{" "}
              <a
                href="https://pixabay.com/service/privacy-policy/"
                className="text-blue-600 underline"
                target="_blank"
                rel="noopener noreferrer"
              >
                Pixabay Privacy Policy
              </a>
            </li>
            <li>
              <strong>Security Measures:</strong> No user-identifiable data is
              shared with Pixabay. The keyword data used for video generation
              remains anonymous and is only used to fetch relevant media from
              their library.
            </li>
          </ul>

          {/* Section for Stable Diffusion API */}
          <h2>2. Stable Diffusion API</h2>
          <p>
            We integrate Stable Diffusion via API to generate images based on
            user-provided prompts. This API allows us to create custom visuals
            that enhance the videos generated from documents.
          </p>
          <ul>
            <li>
              <strong>Data Usage:</strong> Stable Diffusion processes the prompt
              data (text input) provided by users to generate images. No
              personal or identifiable information is transferred during this
              process.
            </li>
            <li>
              <strong>Privacy Policy:</strong>{" "}
              <a
                href="https://stablediffusionweb.com/privacy"
                className="text-blue-600 underline"
                target="_blank"
                rel="noopener noreferrer"
              >
                Stable Diffusion Privacy Policy
              </a>
            </li>
            <li>
              <strong>Security Measures:</strong> The prompt data used for
              generating images is not stored by Stable Diffusion. All data
              transmitted is done so securely, and the API does not retain user
              data after the image generation process is complete.
            </li>
          </ul>

          {/* Section for GenAI API */}
          <h2>3. GenAI (Gemini 1.5 Flash) API</h2>
          <p>
            The GenAI Gemini 1.5 Flash API is used for multiple purposes within
            AURA.ai, including refining the summaries generated by the BART
            model and generating prompts and quiz questions from user documents.
          </p>
          <ul>
            <li>
              <strong>Data Usage:</strong> GenAI processes the text summaries
              and prompts provided by our platform. However, no
              user-identifiable information is sent to or stored by the API. It
              processes non-personal data (such as text inputs) to refine the
              content and generate quizzes.
            </li>
            <li>
              <strong>Privacy Policy:</strong>{" "}
              <a
                href="#"
                className="text-blue-600 underline"
                target="_blank"
                rel="noopener noreferrer"
              >
                Gemini Privacy Policy
              </a>
            </li>
            <li>
              <strong>Security Measures:</strong> All interactions with GenAI
              are encrypted, ensuring the secure transmission of text data.
              GenAI does not retain user data or use it for any purposes beyond
              the immediate processing task.
            </li>
          </ul>

          {/* Data Protection Section */}
          <h2>User Data Protection and Security Measures</h2>
          <ul>
            <li>
              <strong>Data Minimization:</strong> AURA.ai ensures that only the
              necessary data is shared with third-party APIs. Personal or
              identifiable information is never transmitted to external services
              unless explicitly required and approved by the user.
            </li>
            <li>
              <strong>Data Encryption:</strong> All data transferred between
              AURA.ai and the third-party APIs is encrypted using
              industry-standard encryption protocols (e.g., HTTPS, TLS). This
              ensures that user data is protected during transmission.
            </li>
            <li>
              <strong>Compliance with Data Protection Laws:</strong> We ensure
              that all third-party services comply with international data
              protection regulations such as GDPR, CCPA, and any relevant
              regional laws.
            </li>
            <li>
              <strong>User Consent:</strong> Users are informed of our
              third-party integrations and must consent to the use of these
              services. AURA.ai does not share user data without explicit
              permission from the user.
            </li>
            <li>
              <strong>Data Retention:</strong> AURA.ai retains user data only
              for as long as necessary to fulfil the intended purpose.
              Third-party APIs do not retain or use any data beyond the
              completion of their specific tasks.
            </li>
          </ul>

          <h2>How We Protect Your Data</h2>
          <ul>
            <li>
              <strong>Data Access:</strong> User data is stored securely within
              our systems and is accessible only by authorised personnel.
              External APIs are used solely for their intended functionality
              (e.g., generating videos, refining text, or creating quizzes).
            </li>
            <li>
              <strong>Third-Party API Compliance:</strong> We only integrate
              with third-party services that meet strict security standards and
              comply with relevant data privacy regulations. This ensures that
              user data is protected and used responsibly.
            </li>
          </ul>

          <p>
            By using AURA.ai, you acknowledge and agree to the usage of the
            above-mentioned third-party APIs, and that the respective privacy
            policies govern how these external services handle your data.
            AURA.ai remains committed to maintaining the highest standards of
            data protection for all our users.
          </p>
        </div>
      </div>
    </Section>
  );
};

export default PrivacyPolicy;
